"""
Port interface definitions — clean architecture port layer.
Defines Protocol classes that infrastructure implementations must follow.
"""

from __future__ import annotations

from pathlib import Path
from typing import Generator, Iterable, List, Optional, Protocol, Tuple

from localforge.domain.models import FileChunk, FileNode, GenerationLogEntry, ProjectIndex


class LLMPort(Protocol):
    """Port interface abstracting communication with the LLM backend."""

    def stream_completion(self, model: str, prompt: str, system: Optional[str] = None) -> Generator[str, None, None]: ...
    def list_models(self) -> List[str]: ...
    def is_available(self) -> bool: ...


class FileSystemPort(Protocol):
    """Port interface abstracting filesystem operations."""

    def read_text(self, path: Path) -> str: ...
    def write_text(self, path: Path, content: str) -> None: ...
    def list_files(self, root: Path, extensions: Optional[Iterable[str]] = None, ignore_dirs: Optional[Iterable[str]] = None) -> List[Path]: ...
    def build_file_tree(self, root: Path) -> List[FileNode]: ...
    def get_mtime_size(self, path: Path) -> Tuple[float, int]: ...
    def exists(self, path: Path) -> bool: ...


class GitPort(Protocol):
    """Port interface abstracting git operations."""

    def init(self, path: Path) -> None: ...
    def commit_all(self, path: Path, message: str) -> str: ...
    def get_log(self, path: Path, max_entries: int = 20) -> List[dict]: ...
    def get_diff(self, path: Path) -> str: ...
    def get_status(self, path: Path) -> str: ...
    def get_current_branch(self, path: Path) -> str: ...


class IndexPort(Protocol):
    """Port interface abstracting ProjectIndex persistence."""

    def save_chunks(self, path: Path, chunks: List[FileChunk]) -> None: ...
    def load_chunks(self, path: Path) -> List[FileChunk]: ...
    def save_index(self, path: Path, index: ProjectIndex) -> None: ...
    def load_index(self, path: Path) -> Optional[ProjectIndex]: ...
    def append_log_entry(self, path: Path, entry: GenerationLogEntry) -> None: ...
    def load_log_entries(self, path: Path) -> List[GenerationLogEntry]: ...
